

INSERT INTO Sectors (id,Naam,IsActive) VALUES (1,'Arbeid', 1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (2,'Overheidsbedrijven (1-50 personeelsleden)',1,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (3,'Overheidsbedrijven (>50 personeelsleden)',1,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (4,'Private bedrijven (1-50 personeelsleden)',1,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (5,'Private bedrijven (>50 personeelsleden)',1,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (6,'Social profit organisaties (1-50 personeelsleden)',1,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (7,'Social profit organisaties (>50 personeelsleden)',1,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (8,'Externe diensten ter preventie en bescherming op het werk',1,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (9,'Vakbonden',1,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (10,'Meerdere',1,1);
INSERT INTO Sectors (id,Naam,IsActive) VALUES (11,'Gezondheid', 1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (12,'Zelforganisatie (AA, belangengroepen drugs, etc.)',11,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (13,'Centrum geestelijke gezondheid',11,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (14,'Medisch sociaal opvangcentrum (MSOC)',11,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (15,'Dagcentrum',11,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (16,'Therapeutische gemeenschap (TG)',11,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (17,'Crisiscentrum',11,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (18,'Psychiatrische afdeling algemeen ziekenhuis (PAAZ) / psychiatrisch ziekenhuis',11,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (19,'Straathoekwerk',11,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (20,'Lokaal gezondheidsoverleg (LOGO)',11,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (21,'Koepels',11,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (22,'Andere',11,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (23,'Meerdere',11,1);
INSERT INTO Sectors (id,Naam,IsActive) VALUES (24,'Onderwijs', 1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (25,'Basisonderwijs: kleuteronderwijs',24,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (26,'Basisonderwijs: buitengewoon lager onderwijs (BLO)',24,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (27,'Basisonderwijs: lager onderwijs (LO)',24,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (28,'Basisonderwijs: meerdere onderwijsvormen',24,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (29,'Basisonderwijs: andere',24,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (30,'Secundair onderwijs: ASO',24,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (31,'Secundair onderwijs: BSO',24,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (32,'Secundair onderwijs: BuSO',24,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (33,'Secundair onderwijs: deeltijds onderwijs',24,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (34,'Secundair onderwijs: KSO',24,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (35,'Secundair onderwijs: TSO',24,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (36,'Secundair onderwijs: ASO & TSO',24,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (37,'Secundair onderwijs: ASO & BSO',24,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (38,'Secundair onderwijs: TSO & BSO',24,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (39,'Secundair onderwijs: ASO, TSO & BSO',24,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (40,'Secundair onderwijs: andere combinaties van onderwijsvormen',24,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (41,'Secundair onderwijs: andere',24,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (42,'Hoger onderwijs: niet-universitair onderwijs',24,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (43,'Hoger onderwijs: universitair onderwijs',24,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (44,'Centrum voor leerlingenbegeleiding (CLB)',24,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (45,'Medisch pedagogisch instituut (MPI)',24,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (46,'Oudervereniging',24,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (47,'Koepels',24,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (48,'Andere',24,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (49,'Meerdere',24,1);
INSERT INTO Sectors (id,Naam,IsActive) VALUES (50,'Overheid', 1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (51,'internationaal',50,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (52,'Federaal',50,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (53,'Gemeenschap',50,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (54,'Provinciaal',50,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (55,'Regionaal (?: Intergemeentelijke preventiewerker, intercommunale)',50,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (56,'Lokaal (gemeentelijke ambtenaar/dienst, college, ...)',50,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (57,'Andere',50,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (58,'Meerdere',50,1);
INSERT INTO Sectors (id,Naam,IsActive) VALUES (59,'Politie en Justitie', 1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (60,'Gevangenis',59,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (61,'Politie (?: federale politie, lokale politie, politiezone)',59,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (62,'Rechtbank',59,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (63,'Justitiehuis',59,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (64,'Andere',59,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (65,'Meerdere',59,1);
INSERT INTO Sectors (id,Naam,IsActive) VALUES (66,'Vrijetijds- en cultuursector', 1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (67,'port: sportvereniging, -club',66,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (68,'Sport: koepels',66,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (69,'Uitgaanssector: horeca',66,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (70,'Uitgaanssector: dancing, club',66,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (71,'Uitgaanssector: festivals, en manifestatie',66,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (72,'Uitgaanssector: koepels',66,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (73,'Uitgaanssector: andere',66,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (74,'Jeugdwerk: jeugdvereniging, -beweging',66,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (75,'Jeugdwerk: jeugdhuis',66,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (76,'Jeugdwerk: koepels',66,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (77,'Jeugdwerk: andere',66,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (78,'Sociocultureel volwassenenwerk',66,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (79,'Allochtonenorganisaties',66,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (80,'Andere',66,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (81,'Meerdere',66,1);
INSERT INTO Sectors (id,Naam,IsActive) VALUES (82,'Welzijn', 1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (83,'entrum voor algemeen welzijnswerk (CAW): deelwerking jongerenadviescentrum (JAC)',82,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (84,'Centrum voor algemeen welzijnswerk (CAW): deelwerking justitieel welzijnswerk',82,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (85,'Centrum voor algemeen welzijnswerk (CAW): thuislozenzorg',82,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (86,'Centrum voor algemeen welzijnswerk (CAW): andere deelwerking',82,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (87,'Bijzondere jeugdzsec. voorziening bijzondere jeugdzorg',82,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (88,'Bijzondere jeugdzsec. comité bijzondere jeugdzorg (CBJ)',82,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (89,'Bijzondere jeugdzsec. sociale dienst jeugdrechtbank',82,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (90,'Openbaar centrum voor maatschappelijk werk (OCMW)',82,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (91,'Koepels',82,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (92,'Straathoekwerk',82,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (93,'Samenlevingsopbouw (RISO, buurthuis, e.d.)',82,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (94,'Minderhedensector (integratiecentrum, onthaalbureau, opvangcentrum asielzoekers)',82,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (95,'Andere',82,1);
INSERT INTO Sectors (id,Naam,ouder_id,IsActive) VALUES (96,'Meerdere',82,1);
INSERT INTO Sectors (id,Naam,IsActive) VALUES (97,'Algemene bevolking', 1);


