

INSERT INTO Sectors (id,Naam) VALUES (1,'Arbeid');
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (2,'Overheidsbedrijven (1-50 personeelsleden)',1);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (3,'Overheidsbedrijven (>50 personeelsleden)',1);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (4,'Private bedrijven (1-50 personeelsleden)',1);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (5,'Private bedrijven (>50 personeelsleden)',1);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (6,'Social profit organisaties (1-50 personeelsleden)',1);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (7,'Social profit organisaties (>50 personeelsleden)',1);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (8,'Externe diensten ter preventie en bescherming op het werk',1);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (9,'Vakbonden',1);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (10,'Meerdere',1);
INSERT INTO Sectors (id,Naam) VALUES (11,'Gezondheid');
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (12,'Zelforganisatie (AA, belangengroepen drugs, etc.)',11);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (13,'Centrum geestelijke gezondheid',11);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (14,'Medisch sociaal opvangcentrum (MSOC)',11);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (15,'Dagcentrum',11);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (16,'Therapeutische gemeenschap (TG)',11);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (17,'Crisiscentrum',11);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (18,'Psychiatrische afdeling algemeen ziekenhuis (PAAZ) / psychiatrisch ziekenhuis',11);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (19,'Straathoekwerk',11);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (20,'Lokaal gezondheidsoverleg (LOGO)',11);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (21,'Koepels',11);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (22,'Andere',11);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (23,'Meerdere',11);
INSERT INTO Sectors (id,Naam) VALUES (24,'Onderwijs');
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (25,'Basisonderwijs: kleuteronderwijs',24);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (26,'Basisonderwijs: buitengewoon lager onderwijs (BLO)',24);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (27,'Basisonderwijs: lager onderwijs (LO)',24);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (28,'Basisonderwijs: meerdere onderwijsvormen',24);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (29,'Basisonderwijs: andere',24);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (30,'Secundair onderwijs: ASO',24);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (31,'Secundair onderwijs: BSO',24);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (32,'Secundair onderwijs: BuSO',24);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (33,'Secundair onderwijs: deeltijds onderwijs',24);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (34,'Secundair onderwijs: KSO',24);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (35,'Secundair onderwijs: TSO',24);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (36,'Secundair onderwijs: ASO & TSO',24);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (37,'Secundair onderwijs: ASO & BSO',24);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (38,'Secundair onderwijs: TSO & BSO',24);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (39,'Secundair onderwijs: ASO, TSO & BSO',24);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (40,'Secundair onderwijs: andere combinaties van onderwijsvormen',24);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (41,'Secundair onderwijs: andere',24);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (42,'Hoger onderwijs: niet-universitair onderwijs',24);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (43,'Hoger onderwijs: universitair onderwijs',24);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (44,'Centrum voor leerlingenbegeleiding (CLB)',24);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (45,'Medisch pedagogisch instituut (MPI)',24);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (46,'Oudervereniging',24);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (47,'Koepels',24);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (48,'Andere',24);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (49,'Meerdere',24);
INSERT INTO Sectors (id,Naam) VALUES (50,'Overheid');
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (51,'internationaal',50);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (52,'Federaal',50);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (53,'Gemeenschap',50);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (54,'Provinciaal',50);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (55,'Regionaal (?: Intergemeentelijke preventiewerker, intercommunale)',50);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (56,'Lokaal (gemeentelijke ambtenaar/dienst, college, ...)',50);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (57,'Andere',50);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (58,'Meerdere',50);
INSERT INTO Sectors (id,Naam) VALUES (59,'Politie en Justitie');
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (60,'Gevangenis',59);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (61,'Politie (?: federale politie, lokale politie, politiezone)',59);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (62,'Rechtbank',59);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (63,'Justitiehuis',59);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (64,'Andere',59);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (65,'Meerdere',59);
INSERT INTO Sectors (id,Naam) VALUES (66,'Vrijetijds- en cultuursector');
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (67,'port: sportvereniging, -club',66);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (68,'Sport: koepels',66);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (69,'Uitgaanssector: horeca',66);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (70,'Uitgaanssector: dancing, club',66);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (71,'Uitgaanssector: festivals, en manifestatie',66);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (72,'Uitgaanssector: koepels',66);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (73,'Uitgaanssector: andere',66);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (74,'Jeugdwerk: jeugdvereniging, -beweging',66);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (75,'Jeugdwerk: jeugdhuis',66);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (76,'Jeugdwerk: koepels',66);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (77,'Jeugdwerk: andere',66);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (78,'Sociocultureel volwassenenwerk',66);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (79,'Allochtonenorganisaties',66);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (80,'Andere',66);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (81,'Meerdere',66);
INSERT INTO Sectors (id,Naam) VALUES (82,'Welzijn');
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (83,'entrum voor algemeen welzijnswerk (CAW): deelwerking jongerenadviescentrum (JAC)',82);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (84,'Centrum voor algemeen welzijnswerk (CAW): deelwerking justitieel welzijnswerk',82);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (85,'Centrum voor algemeen welzijnswerk (CAW): thuislozenzorg',82);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (86,'Centrum voor algemeen welzijnswerk (CAW): andere deelwerking',82);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (87,'Bijzondere jeugdzsec. voorziening bijzondere jeugdzorg',82);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (88,'Bijzondere jeugdzsec. comité bijzondere jeugdzorg (CBJ)',82);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (89,'Bijzondere jeugdzsec. sociale dienst jeugdrechtbank',82);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (90,'Openbaar centrum voor maatschappelijk werk (OCMW)',82);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (91,'Koepels',82);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (92,'Straathoekwerk',82);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (93,'Samenlevingsopbouw (RISO, buurthuis, e.d.)',82);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (94,'Minderhedensector (integratiecentrum, onthaalbureau, opvangcentrum asielzoekers)',82);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (95,'Andere',82);
INSERT INTO Sectors (id,Naam,ouder_id) VALUES (96,'Meerdere',82);
INSERT INTO Sectors (id,Naam) VALUES (97,'Algemene bevolking');



