UPDATE Activity SET TotalParticipants = 2 WHERE TotalParticipants = 11;
UPDATE Activity SET TotalParticipants = 6 WHERE TotalParticipants = 2;
UPDATE Activity SET TotalParticipants = 17 WHERE TotalParticipants = 3;
UPDATE Activity SET TotalParticipants = 37 WHERE TotalParticipants = 4;
UPDATE Activity SET TotalParticipants = 75 WHERE TotalParticipants = 5;
UPDATE Activity SET TotalParticipants = 150 WHERE TotalParticipants = 6;
update VadGingerUser set passwordHash = '123456';
update VadGingerUser set role = 1 where userID in ('vadmge');
update VadGingerUser set role = 3 where userID in ('vadjro');
update VadGingerUser set role = 3 where userID in ('jefwau');

update ActivityType set id = 999 where Naam = 'Andere actie';
Update Items set Naam = 'Geen specifiek middel als item' where Naam = 'Middelengebruik algemeen';
delete from Locations where ouder_id = 1 and Naam in ('LIMAL','WAVRE','BIERGES','LA HULPE','GLIMES','INCOURT','OPPREBAIS','PIETREBAIS','ROUX-MIROIR','BEAUVECHAIN','HAMME-MILLE','L\'ECLUSE','NODEBAIS','TOURINNES-LA-GROSSE','BONLEZ','CHAUMONT-GISTOUX','CORROY-LE-GRAND','DION-LE-MONT (CHAUMONT-GISTOUX)','DION-LE-VAL (CHAUMONT-GISTOUX)','DION-VALMONT','LONGUEVILLE','RIXENSART','ROSIERES','GENVAL','OTTIGNIES','OTTIGNIES-LOUVAIN-LA-NEUVE','CEROUX-MOUSTY','LIMELETTE','LOUVAIN-LA-NEUVE','ENINES','FOLX-LES-CAVES','JANDRAIN-JANDRENOUILLE','JAUCHE','MARILLES','NODUWEZ','ORP-JAUCHE','ORP-LE-GRAND','HELECINE','LINSMEAU','NEERHEYLISSEM','OPHEYLISSEM','MALEVES-SAINTE-MARIE-WASTINES','ORBAIS','PERWEZ','THOREMBAIS-LES-BEGUINES','THOREMBAIS-SAINT-TROND','AUTRE-EGLISE','BOMAL (BT.)','GEEST-GEROMPONT-PETIT-ROSIERE','GEROMPONT','GRAND-ROSIERE-HOTTOMONT','HUPPAYE','MONT-SAINT-ANDRE','RAMILLIES','DONGELBERG','JAUCHELETTE','JODOIGNE','JODOIGNE-SOUVERAINE','LATHUY','MELIN','PIETRAIN','SAINT-JEAN-GEEST','SAINT-REMY-GEEST','ZETRUD-LUMAY','COUTURE-SAINT-GERMAIN','LASNE','LASNE-CHAPELLE-SAINT-LAMBERT','MARANSART','OHAIN','PLANCENOIT','ARCHENNES','BIEZ','BOSSUT-GOTTECHAIN','GREZ-DOICEAU','NETHEN','MONSTREUX','NIVELLES','BAULERS','THINES','BORNIVAL','WATERLOO','BRAINE-L\'ALLEUD','OPHAIN-BOIS-SEIGNEUR-ISAAC','LILLOIS-WITTERZEE','BIERGHES','QUENAST','REBECQ','REBECQ-ROGNON','CORBAIS','HEVILLERS','MONT-SAINT-GUIBERT','BRAINE-LE-CHATEAU','WAUTHIER-BRAINE','CHASTRE','CHASTRE-VILLEROUX-BLANMONT','CORTIL-NOIRMONT','GENTINNES','SAINT-GERY','NIL-SAINT-VINCENT-SAINT-MARTIN','TOURINNES-SAINT-LAMBERT','WALHAIN','WALHAIN-SAINT-PAUL','ITTRE','VIRGINAL-SAMME','HAUT-ITTRE','BAISY-THY','BOUSVAL','GENAPPE','LOUPOIGNE','VIEUX-GENAPPE','GLABAIS','WAYS','HOUTAIN-LE-VAL','CLABECQ','OISQUERCQ','SAINTES','TUBIZE','COURT-SAINT-ETIENNE','MARBAIS (BT.)','MELLERY','SART-DAMES-AVELINES','TILLY','VILLERS-LA-VILLE');
update Locations set Naam = UPPER(Naam) where ouder_id = 1;
update ActivityTypeJunction set activityTypeId_id = 999 where activityTypeId_id = 19;
update Evaluvation_Type set EvalType = 'Schriftelijk' where EvalType = 'Schriftel';

UPDATE Locations SET Naam=(REPLACE (Naam, '-$',''));
UPDATE Locations SET Naam=(REPLACE (Naam,'Regionaal O', 'RegiOOO'));
UPDATE Locations SET Naam=(REPLACE (Naam,'Regionaal', 'Regionaal (clusters)'));
UPDATE Locations SET Naam=(REPLACE (Naam,'RegiOOO', 'Regionaal O'));
