USE  [test14]
SET IDENTITY_INSERT  [test14].[dbo].[Locations] ON
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (2906,' ',1, 1,1)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (2908,'Vlaamse Ardennen',1, 42,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2908,2873)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2908,2138)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2908,2844)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2908,2849)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2908,2881)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2908,2747)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2908,2825)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2908,2330)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2908,1515)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2908,1321)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (2920,'Hageland',1, 42,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2920,2739)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2920,846)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2920,2625)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2920,2247)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (2926,'samenwerking EKASI',1, 2,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2926,2014)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2926,2535)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2926,1532)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2926,639)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2926,1258)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2926,2320)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (2934,'Interlokale Vereniging West Meetjesland',1, 2,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2934,2014)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2934,2535)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2934,1532)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (2939,'samenwerking Drugpunt',1, 2,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2939,2014)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2939,2535)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2939,1532)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2939,2860)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2939,2878)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2939,2334)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2939,2861)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2939,1763)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (2949,'samenwerking ELZA',1, 2,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2949,2014)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2949,2535)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2949,1532)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2949,2356)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2949,2859)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2949,2853)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2949,92)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (2958,'Meetjesland',1, 2,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2958,2014)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2958,2535)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2958,1532)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2958,639)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2958,2320)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2958,1258)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2958,2356)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2958,92)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2958,1505)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2958,2869)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (2970,'West-Limburg',1, 42,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2970,222)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2970,2868)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2970,2851)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2970,1890)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2970,2257)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2970,2451)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (2978,'AKM',1, 42,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2978,2014)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2978,2535)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2978,1532)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (2983,'WELZIJNSREGIO NOORD-LIMBURG',1, 7,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2983,2301)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2983,1959)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2983,2789)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2983,2793)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2983,1481)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2983,997)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2983,2092)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2983,1038)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (2993,'JAC LOMMEL',1, 7,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2993,1481)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2993,2301)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2993,1959)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2993,2793)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2993,2092)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2993,1038)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2993,997)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2993,2503)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (2993,2789)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3004,'REGIO NOORD-LIMBURG',1, 7,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3004,2301)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3004,2789)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3004,1959)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3004,2793)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3004,997)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3004,1481)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3004,2092)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3013,'WEST LIMBURG',1, 7,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3013,222)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3013,2868)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3013,2851)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3013,1890)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3013,2451)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3013,1411)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3021,'maasland',1, 7,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3021,1907)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3021,1910)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3021,2666)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3021,2417)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3021,2556)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3028,'KBVB WEST LIMBURG',1, 7,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3028,222)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3028,1411)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3028,1890)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3028,2451)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3028,2257)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3028,2868)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3028,2851)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3028,1610)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3038,'KLM',1, 3,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3038,2065)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3038,2407)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3038,1912)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3043,'DSZ',1, 11,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3043,2739)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3043,2247)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3047,'KASTZE',1, 3,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3047,1770)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3047,2411)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3047,2854)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3052,'Maasland',1, 42,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3052,2666)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3052,1910)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3052,2556)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3057,'Regionale welzijnscommissie Oostende',1, 42,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3057,2842)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3057,2858)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3057,2765)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3057,2753)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3057,374)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3057,1657)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3057,1191)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3066,'Klein Brabant',1, 26,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3066,2743)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3066,2162)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3066,2284)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3071,'ROM',1, 26,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3071,2686)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3071,1441)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3071,1048)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3071,320)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3077,'regio Leuven + Provincie + intergemeentelijke prev',1, 40,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3077,1427)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3077,2625)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3077,2739)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3082,'regio drugpunt',1, 8,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3082,2860)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3082,2878)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3082,1763)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3082,2861)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3082,2334)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3089,'Regio Lokeren-Berlare-Zele',1, 8,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3089,2530)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3089,2850)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3089,1477)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3094,'Regio AKM',1, 8,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3094,2014)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3094,2535)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3094,1532)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3099,'Regio Rhode&Schelde',1, 8,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3099,1615)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3099,2240)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3099,1104)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3104,'Regio Elza',1, 8,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3104,2356)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3104,92)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3104,2853)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3104,2859)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3110,'regio EEKASI',1, 8,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3110,639)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3110,1258)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3110,2320)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3115,'Regio Wetteren_Laarne_Wichelen',1, 8,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3115,2772)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3115,1342)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3115,2779)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3120,'Regio INDRA',1, 8,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3120,7)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3120,2631)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3120,2705)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3120,1053)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3120,571)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3127,'Aalter Knesselare',1, 8,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3127,2014)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3127,2535)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3131,'RWO regio Sint Niklaas',1, 8,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3131,2340)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3131,1477)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3131,2661)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3131,2341)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3131,2412)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3131,2174)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3131,2481)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3131,2676)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3141,'Halle-Vilvoorde',1, 3,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3141,979)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3141,2615)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3141,1684)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3146,'Brussel-Halle-Vilvoorde',1, 3,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3146,410)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3146,979)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3146,2615)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3146,1684)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3152,'MIdden en Zuid- West-Vlaanderen',1, 22,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3152,1315)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3152,2167)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3156,'Ternat-Roosdaal-Asse-Affligem',1, 3,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3156,2447)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3156,2425)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3156,1684)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3156,2444)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3162,'Brussels Gewest',1, 42,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3162,410)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3162,426)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3162,723)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3162,731)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3162,1232)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3162,1946)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3162,2236)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3162,2727)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3162,834)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3162,2305)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3174,'Intergemeentelijke samenwerking Zele-Berlare',1, 10,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3174,2530)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3174,2850)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3178,'Regio Waas en Dender',1, 10,1)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3180,'Intergmeentelijk St-Niklaas - Beveren',1, 10,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3180,2661)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3180,2340)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3184,'zorgregio VAGGA Ketsstraat',1, 4,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3184,63)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3184,371)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3184,2248)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3184,2766)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3184,1731)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3184,2792)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3184,2886)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3184,2322)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3184,1256)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3184,712)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3196,'Regio Waasland',1, 10,1)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3198,'Vilvoorde en rand',1, 3,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3198,2615)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3198,2854)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3198,2065)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3198,940)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3198,1519)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3198,2411)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3198,1770)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3207,'Asse en rand',1, 3,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3207,1684)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3207,2752)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3207,1916)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3207,2351)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3207,1630)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3207,2444)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3207,2447)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3216,'ECAT Sint-Niklaas & Dendermonde',1, 10,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3216,2297)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3216,2340)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3220,'RWR Ieper',1, 28,1)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3222,'Rhode en Schelde',1, 21,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3222,1615)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3222,2240)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3222,1104)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3227,'Pajottenland',1, 3,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3227,1850)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3227,2646)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3227,260)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3227,1087)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3227,1978)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3227,2336)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3235,'Faciliteitengemeenten (PW Haviland)',1, 3,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3235,2752)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3235,1318)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3235,2776)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3235,622)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3235,1460)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3242,'KASTZE',1, 19,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3242,2854)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3242,1770)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3242,2411)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3247,'haviland',1, 15,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3247,622)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3247,1460)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3247,1318)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3247,2776)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3247,2752)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3254,'intergemeentelijke drugpreventie Gooik',1, 13,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3254,2646)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3254,1087)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3254,1850)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3254,260)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3254,1978)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3254,2336)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3262,'groot leuven',1, 23,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3262,1262)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3262,2150)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3262,2761)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3262,322)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3262,236)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3262,2520)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3262,1427)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3262,1915)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3262,1312)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3273,'hageland',1, 23,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3273,2739)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3273,199)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3273,2484)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3273,937)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3273,2247)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3273,2326)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3273,846)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3273,2625)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3283,'Regio Mechelen',1, 26,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3283,2686)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3286,'Regio Antwerpen/Mechelen',1, 26,1)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3288,'Regio Mechelen/Turnhout',1, 26,1)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3290,'BODUKAP',1, 26,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3290,2109)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3290,625)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3290,2312)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3290,2045)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3296,'Rupel',1, 26,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3296,320)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3296,2242)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3296,1799)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3296,2445)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3296,1059)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3303,'Halle-Vilvoorde',1, 42,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3303,979)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3303,187)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3303,2351)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3303,1684)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3303,2615)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3303,2846)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3303,1957)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3303,2295)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3303,2344)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3303,1978)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3315,'Regio Oostende',1, 28,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3315,2842)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3315,2858)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3315,374)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3315,1657)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3321,'politiezone spoorkin',1, 28,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3321,2874)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3321,2348)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3321,2089)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3326,'kust',1, 28,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3326,374)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3326,1306)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3326,2842)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3326,1657)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3326,564)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3326,2753)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3326,2531)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3326,2827)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3326,2309)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3337,'Interlokale vereniging drugpreventie Noord-Pajot',1, 43,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3337,1684)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3337,2444)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3337,2425)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3337,2447)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3343,'Interlokale vereniging drugpreventie Pajottenland',1, 43,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3343,1850)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3343,2646)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3343,260)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3343,1087)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3343,2336)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3343,1978)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3351,'Interlokale vereniging drugpreventie Haacht-Bo-Kee',1, 43,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3351,2761)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3351,322)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3351,1262)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3356,'Interlokale vereniging drugpreventie Haviland',1, 43,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3356,2752)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3356,1318)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3356,2776)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3356,622)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3356,1460)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3363,'Interlokale vereniging drugpreventie KASTZE',1, 43,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3363,2854)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3363,1770)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3363,2411)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3368,'Interlokale vereniging drugpreventie BRT',1, 43,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3368,236)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3368,2150)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3368,2520)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3373,'ACV Gent-Eeklo',1, 8,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3373,856)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3373,639)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3373,2860)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3378,'Regionaal Overleg Drugs Mechelen',1, 32,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3378,2686)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3378,320)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3378,1441)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3378,1048)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3384,'Aalter-Knesselare',1, 2,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3384,2014)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3384,2535)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3388,'Regionaal Overleg Mechelen 8/1/2009',1, 24,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3388,320)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3388,1441)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3388,1048)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3388,2686)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3394,'CGG-regio Antwerpen - De Pont',1, 42,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3394,1441)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3394,2686)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3394,320)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3399,'Regionaal Overleg Drugpreventie 20/4/2009',1, 24,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3399,320)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3399,1441)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3399,2686)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3399,1048)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3405,'Regionaal Overleg Drugpreventie 13/7/2009',1, 24,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3405,320)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3405,1441)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3405,2686)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3405,1048)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3411,'Regionaal Overleg Drugpreventie 16/12/2009',1, 24,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3411,320)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3411,2686)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3411,1441)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3411,1048)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3417,'Regio Brugge',1, 22,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3417,1306)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3417,2847)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3417,2671)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3417,2308)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3417,2764)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3417,2764)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3425,'RWR Veurne-Diksmuide',1, 28,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3425,2874)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3425,2826)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3425,2845)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3425,2839)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3425,1635)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3425,2348)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3425,2089)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3425,2309)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3425,2827)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3425,564)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3437,'zorgregio Roeselare',1, 22,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3437,1245)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3437,2167)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3437,1650)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3437,79)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3437,2008)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3437,2164)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3437,2884)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3437,1436)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3437,1896)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3437,1197)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3449,'Halle-Vilvoorde',1, 15,1)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3451,'Waasland',1, 42,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3451,2340)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3454,'CGG-regio Middelpunt',1, 42,1)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3456,'CGG-regio VAGGA-Altox',1, 42,1)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3458,'CGG-regio Gent',1, 42,1)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3460,'CGG-regio Limburg',1, 42,1)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3462,'CGG-regio Asse-Vilvoorde',1, 42,1)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3464,'CGG-regio Leuven',1, 42,1)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3466,'CGG-regio Sint-Niklaas',1, 42,1)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3468,'CGG-regio Brussel',1, 42,1)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3470,'CGG-regio Turnhout',1, 42,1)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3472,'haacht',1, 23,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3472,1262)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3472,2761)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3472,322)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3477,'brt',1, 23,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3477,236)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3477,2150)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3477,2520)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3482,'haviland',1, 23,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3482,1318)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3482,2776)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3482,1460)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3482,622)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3482,2752)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3489,'kastze',1, 23,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3489,1770)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3489,2411)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3489,2854)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3494,'pajottenland',1, 23,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3494,260)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3494,2646)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3494,1087)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3494,1850)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3494,2336)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3494,1978)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3502,'tarl',1, 23,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3502,2425)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3502,2447)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3502,2444)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3502,1684)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3508,'Drugpunt-regio',1, 9,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3508,2860)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3508,2878)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3508,2861)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3508,2334)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3508,1763)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3515,'Regio Turnhout',1, 25,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3515,1940)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3515,2526)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3515,2480)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3515,2073)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3521,'Regio Geel',1, 25,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3521,838)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3521,2866)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3521,1861)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3521,2656)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3521,1596)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3528,'Regio Mol',1, 25,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3528,147)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3528,1678)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3528,2096)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3528,577)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3534,'Regio Herentals',1, 25,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3534,1828)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3534,1078)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3534,943)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3539,'Regio Beerse',1, 25,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3539,2638)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3539,2740)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3539,2653)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3544,'Regio Hoogstraten',1, 25,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3544,1147)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3544,1637)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3544,133)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3544,2107)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3550,'Regio Herselt',1, 25,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3550,2066)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3550,2767)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3554,'Kempen',1, 25,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3554,2526)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3554,838)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3554,1678)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3554,1828)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3554,2066)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3554,1147)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3554,80)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3554,2638)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3564,'Regio Dendermonde',1, 8,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3564,2297)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3564,2786)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3564,1900)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3564,1672)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3564,2676)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3571,'JES',1, 33,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3571,410)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3571,856)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3571,63)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3576,'Halle en rand',1, 3,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3576,979)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3576,187)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3576,2295)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3581,'Brussel-Halle',1, 33,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3581,979)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3581,2615)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3581,940)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3581,410)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3587,'Pajottenland',1, 34,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3587,979)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3587,187)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3591,'Zorgregio Kortrijk',1, 22,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3591,1315)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3591,1325)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3591,2709)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3591,1010)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3591,1405)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3591,566)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3599,'Politiezone WOKRA',1, 15,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3599,1318)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3599,2776)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3603,'Regio Aalst',1, 10,1)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3605,'Regio Dendermonde',1, 10,1)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3607,'Kempen',1, 12,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3607,838)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3607,1678)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3607,1828)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3607,2526)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3613,'Regio LOGO Waasland',1, 10,1)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3615,'ALLeRT',1, 3,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3615,2444)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3615,1437)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3615,2336)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3615,2425)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3615,2447)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3622,'Faciliteitengemeenten',1, 15,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3622,622)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3622,1460)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3622,1318)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3622,2752)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3622,2776)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3629,'Politiezone Rode',1, 15,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3629,2295)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3629,1460)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3629,622)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3634,'TARL',1, 3,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3634,2447)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3634,2444)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3634,2425)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3634,1437)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3640,'Voorkempen',1, 4,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3640,2322)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3640,2830)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3644,'Logo regio dender',1, 10,1)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3646,'logo regio gezond plus',1, 10,1)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3648,'Politiezone ARRO Ieper',1, 22,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3648,2303)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3648,1807)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3648,2015)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3648,1646)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3648,1717)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3648,2090)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3648,2770)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3648,2812)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3648,2760)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3648,2871)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3660,'regio leieland',1, 22,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3660,2576)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3660,2684)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3660,566)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3660,1010)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3660,1315)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3660,1325)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3660,2082)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3660,2394)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3660,2709)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3660,2760)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3672,'gerechtelijk arrondisement Ieper',1, 22,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3672,2303)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3672,2760)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3672,1807)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3672,1646)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3672,2090)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3672,2874)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3672,2826)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3672,1635)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3672,2827)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3672,2309)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3684,'regio welzijnsraad Ieper',1, 22,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3684,2303)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3684,1807)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3684,2760)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3684,2090)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3684,2812)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3684,1646)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3684,2015)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3684,2871)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3694,'regio logo midden-west-vlaanderen',1, 22,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3694,79)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3694,2826)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3694,1807)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3694,1635)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3694,1145)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3694,2303)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3694,1197)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3694,1245)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3694,2845)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3694,1405)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3706,'Regio CLB GO Tielt',1, 22,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3706,2482)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3706,2709)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3706,2860)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3706,639)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3706,2861)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3713,'Regio LOP Hamme',1, 10,1)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3715,'Centrumsteden',1, 35,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3715,2167)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3715,1306)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3715,1315)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3715,2842)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3721,'MSOC',1, 35,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3721,2167)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3721,2842)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3721,1315)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3726,'CLUSTER_ONE1',1, 18,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3726,13)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3726,31)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3726,1306)
INSERT INTO [dbo].[Locations] ([id],[Naam],[IsCluster], [centrumId_id],[IsActive]) VALUES (3731,'Politiezone AMOW',1, 15,1)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3731,1684)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3731,1630)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3731,1916)
INSERT INTO [dbo].[CityClusterJunction] ([clusterId_id],[cityId_id]) VALUES (3731,2752)

SET IDENTITY_INSERT  [test14].[dbo].[Locations] OFF
GO