

INSERT INTO Locations (id,Naam,IsCluster) VALUES (2906,' ',1);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (2908,'Vlaamse Ardennen',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2909,'ELENE:::ERWETEGEM:::GODVEERDEGEM:::GROTENBERGE:::LEEUWERGEM:::OOMBERGEN (ZOTTEGEM):::SINT-GORIKS-OUDENHOVE:::SINT-MARIA-OUDENHOVE (ZOTTEGEM):::STRIJPEN:::VELZEKE-RUDDERSHOVE:::ZOTTEGEM',2908);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2910,'RENAIX:::RONSE',2908);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2911,'GERAARDSBERGEN:::GOEFERDINGE:::MOERBEKE:::NEDERBOELARE:::ONKERZELE:::OPHASSELT:::OVERBOELARE:::VIANE:::ZARLARDINGE',2908);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2912,'BRAKEL:::ELST:::EVERBEEK:::MICHELBEKE:::NEDERBRAKEL:::OPBRAKEL:::SINT-MARIA-OUDENHOVE (BRAKEL):::ZEGELSEM',2908);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2913,'BEERLEGEM:::DIKKELE:::HUNDELGEM:::MEILEGEM:::MUNKZWALM:::PAULATEM:::ROBORST:::ROZEBEKE:::SINT-BLASIUS-BOEKEL:::SINT-DENIJS-BOEKEL:::SINT-MARIA-LATEM:::ZWALM',2908);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2914,'BEVERE:::EDELARE:::EINE:::ENAME:::HEURNE:::LEUPEGEM:::MATER:::MELDEN:::MULLEM:::NEDERENAME:::OOIKE (OUDENAARDE):::OUDENAARDE:::VOLKEGEM:::WELDEN',2908);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2915,'HERZELE:::HILLEGEM:::SINT-ANTELINKS:::SINT-LIEVENS-ESSE:::STEENHUIZE-WIJNHUIZE:::WOUBRECHTEGEM',2908);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2916,'DEFTINGE:::LIERDE:::SINT-MARIA-LIERDE',2908);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2917,'ETIKHOVE:::MAARKE-KERKEM:::MAARKEDAL',2908);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2918,'KRUISHOUTEM',2908);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (2920,'Hageland',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2921,'DEURNE (BT.):::DIEST:::SCHAFFEN:::WEBBEKOM',2920);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2922,'AARSCHOT:::GELRODE',2920);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2923,'BOST:::GOETSENHOVEN:::HAKENDOVER:::KUMTICH:::OORBEEK:::OPLINTER:::SINT-MARGRIETE-HOUTEM (TIENEN):::TIENEN:::VISSENAKEN',2920);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2924,'SCHERPENHEUVEL:::SCHERPENHEUVEL-ZICHEM',2920);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (2926,'samenwerking EKASI',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2927,'AALTER:::LOTENHULLE:::POEKE',2926);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2928,'KNESSELARE:::URSEL',2926);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2929,'MALDEGEM',2926);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2930,'EEKLO',2926);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2931,'KAPRIJKE',2926);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2932,'SINT-LAUREINS',2926);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (2934,'Interlokale Vereniging West Meetjesland',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2935,'AALTER:::LOTENHULLE:::POEKE',2934);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2936,'KNESSELARE:::URSEL',2934);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2937,'MALDEGEM',2934);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (2939,'samenwerking Drugpunt',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2940,'AALTER:::LOTENHULLE:::POEKE',2939);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2941,'KNESSELARE:::URSEL',2939);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2942,'MALDEGEM',2939);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2943,'ASTENE:::BACHTE-MARIA-LEERNE:::DEINZE:::GOTTEM:::GRAMMENE:::MEIGEM:::PETEGEM-AAN-DE-LEIE:::SINT-MARTENS-LEERNE:::VINKT:::WONTERGEM:::ZEVEREN',2939);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2944,'MACHELEN (O.-VL.):::OLSENE:::ZULTE',2939);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2945,'SINT-MARTENS-LATEM',2939);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2946,'DE PINTE:::ZEVERGEM',2939);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2947,'EKE:::NAZARETH',2939);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (2949,'samenwerking ELZA',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2950,'AALTER:::LOTENHULLE:::POEKE',2949);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2951,'KNESSELARE:::URSEL',2949);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2952,'MALDEGEM',2949);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2953,'ERTVELDE:::EVERGEM:::KLUIZEN:::SLEIDINGE',2949);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2954,'BEERVELDE:::LOCHRISTI:::ZAFFELARE:::ZEVENEKEN',2949);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2955,'ZELZATE',2949);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2956,'ASSENEDE',2949);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (2958,'Meetjesland',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2959,'AALTER:::LOTENHULLE:::POEKE',2958);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2960,'KNESSELARE:::URSEL',2958);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2961,'MALDEGEM',2958);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2962,'EEKLO',2958);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2963,'SINT-LAUREINS',2958);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2964,'KAPRIJKE',2958);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2965,'ERTVELDE:::EVERGEM:::KLUIZEN:::SLEIDINGE',2958);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2966,'ASSENEDE',2958);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2967,'LOVENDEGEM',2958);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2968,'ZOMERGEM',2958);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (2970,'West-Limburg',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2971,'BERINGEN',2970);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2972,'BOLDERBERG (HEUSDEN-ZOLDER):::HEUSDEN (LIMB.):::HEUSDEN-ZOLDER:::ZOLDER',2970);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2973,'HALEN:::LOKSBERGEN:::ZELEM',2970);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2974,'HAM:::KWAADMECHELEN:::OOSTHAM',2970);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2975,'BERBROEK:::DONK:::HERK-DE-STAD:::SCHULEN',2970);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2976,'TESSENDERLO',2970);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (2978,'AKM',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2979,'AALTER:::LOTENHULLE:::POEKE',2978);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2980,'KNESSELARE:::URSEL',2978);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2981,'MALDEGEM',2978);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (2983,'WELZIJNSREGIO NOORD-LIMBURG',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2984,'NEERPELT:::SINT-HUIBRECHTS-LILLE',2983);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2985,'OVERPELT',2983);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2986,'GROTE-BROGEL:::KLEINE-BROGEL:::PEER:::WIJCHMAAL',2983);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2987,'ELLIKOM:::GRUITRODE:::MEEUWEN:::MEEUWEN-GRUITRODE:::NEERGLABBEEK:::WIJSHAGEN',2983);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2988,'LOMMEL',2983);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2989,'ACHEL:::HAMONT:::HAMONT-ACHEL',2983);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2990,'BOCHOLT:::KAULILLE:::REPPEL',2983);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2991,'HECHTEL:::HECHTEL-EKSEL',2983);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (2993,'JAC LOMMEL',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2994,'LOMMEL',2993);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2995,'NEERPELT:::SINT-HUIBRECHTS-LILLE',2993);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2996,'OVERPELT',2993);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2997,'ELLIKOM:::GRUITRODE:::MEEUWEN:::MEEUWEN-GRUITRODE:::NEERGLABBEEK:::WIJSHAGEN',2993);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2998,'BOCHOLT:::KAULILLE:::REPPEL',2993);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (2999,'HECHTEL:::HECHTEL-EKSEL',2993);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3000,'ACHEL:::HAMONT:::HAMONT-ACHEL',2993);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3001,'BEEK:::BREE:::GERDINGEN:::OPITTER:::TONGERLO (LIMB.)',2993);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3002,'GROTE-BROGEL:::KLEINE-BROGEL:::PEER:::WIJCHMAAL',2993);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3004,'REGIO NOORD-LIMBURG',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3005,'NEERPELT:::SINT-HUIBRECHTS-LILLE',3004);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3006,'GROTE-BROGEL:::KLEINE-BROGEL:::PEER:::WIJCHMAAL',3004);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3007,'OVERPELT',3004);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3008,'ELLIKOM:::GRUITRODE:::MEEUWEN:::MEEUWEN-GRUITRODE:::NEERGLABBEEK:::WIJSHAGEN',3004);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3009,'ACHEL:::HAMONT:::HAMONT-ACHEL',3004);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3010,'LOMMEL',3004);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3011,'BOCHOLT:::KAULILLE:::REPPEL',3004);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3013,'WEST LIMBURG',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3014,'BERINGEN',3013);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3015,'BOLDERBERG (HEUSDEN-ZOLDER):::HEUSDEN (LIMB.):::HEUSDEN-ZOLDER:::ZOLDER',3013);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3016,'HALEN:::LOKSBERGEN:::ZELEM',3013);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3017,'HAM:::KWAADMECHELEN:::OOSTHAM',3013);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3018,'TESSENDERLO',3013);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3019,'LEOPOLDSBURG',3013);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3021,'maasland',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3022,'KESSENICH:::KINROOI:::MOLENBEERSEL:::OPHOVEN',3021);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3023,'MAASEIK:::NEEROETEREN:::OPOETEREN',3021);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3024,'EISDEN:::LEUT:::MAASMECHELEN:::MECHELEN-AAN-DE-MAAS:::MEESWIJK:::OPGRIMBIE:::VUCHT',3021);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3025,'DILSEN-STOKKEM:::ELEN:::LANKLAAR:::ROTEM:::STOKKEM',3021);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3026,'GELLIK:::LANAKEN:::NEERHAREN:::VELDWEZELT',3021);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3028,'KBVB WEST LIMBURG',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3029,'BERINGEN',3028);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3030,'LEOPOLDSBURG',3028);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3031,'HAM:::KWAADMECHELEN:::OOSTHAM',3028);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3032,'TESSENDERLO',3028);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3033,'BERBROEK:::DONK:::HERK-DE-STAD:::SCHULEN',3028);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3034,'BOLDERBERG (HEUSDEN-ZOLDER):::HEUSDEN (LIMB.):::HEUSDEN-ZOLDER:::ZOLDER',3028);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3035,'HALEN:::LOKSBERGEN:::ZELEM',3028);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3036,'LINKHOUT:::LUMMEN:::MELDERT (LIMB.)',3028);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3038,'KLM',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3039,'KAPELLE-OP-DEN-BOS:::NIEUWENRODE:::RAMSDONK',3038);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3040,'LONDERZEEL:::MALDEREN:::STEENHUFFEL',3038);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3041,'BRUSSEGEM (MEISE):::MEISE:::OPPEM (MEISE)',3038);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3043,'DSZ',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3044,'DEURNE (BT.):::DIEST:::SCHAFFEN:::WEBBEKOM',3043);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3045,'SCHERPENHEUVEL:::SCHERPENHEUVEL-ZICHEM',3043);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3047,'KASTZE',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3048,'BERG (BT.):::BUKEN:::KAMPENHOUT:::NEDEROKKERZEEL',3047);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3049,'MELSBROEK:::PERK:::STEENOKKERZEEL',3047);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3050,'EPPEGEM:::ZEMST',3047);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3052,'Maasland',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3053,'EISDEN:::LEUT:::MAASMECHELEN:::MECHELEN-AAN-DE-MAAS:::MEESWIJK:::OPGRIMBIE:::VUCHT',3052);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3054,'MAASEIK:::NEEROETEREN:::OPOETEREN',3052);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3055,'GELLIK:::LANAKEN:::NEERHAREN:::VELDWEZELT',3052);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3057,'Regionale welzijnscommissie Oostende',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3058,'OOSTENDE:::STENE:::ZANDVOORDE (OOSTENDE)',3057);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3059,'GISTEL:::MOERE:::SNAASKERKE:::ZEVEKOTE',3057);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3060,'ETTELGEM:::OUDENBURG:::ROKSEM:::WESTKERKE',3057);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3061,'DE HAAN:::KLEMSKERKE:::WENDUINE',3057);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3062,'BREDENE',3057);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3063,'MIDDELKERKE',3057);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3064,'BEKEGEM:::EERNEGEM:::ICHTEGEM',3057);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3066,'Klein Brabant',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3067,'BORNEM:::HINGENE:::MARIEKERKE (BORNEM):::WEERT',3066);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3068,'BREENDONK:::LIEZELE:::PUURS:::RUISBROEK (ANTW.)',3066);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3069,'LIPPELO:::OPPUURS:::SINT-AMANDS',3066);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3071,'ROM',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3072,'MECHELEN:::WALEM',3071);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3073,'KONINGSHOOIKT:::LIER',3071);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3074,'HALLAAR:::HEIST-OP-DEN-BERG',3071);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3075,'BOOM',3071);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3077,'regio Leuven + Provincie + intergemeentelijke prev',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3078,'LEUVEN',3077);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3079,'BOST:::GOETSENHOVEN:::HAKENDOVER:::KUMTICH:::OORBEEK:::OPLINTER:::SINT-MARGRIETE-HOUTEM (TIENEN):::TIENEN:::VISSENAKEN',3077);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3080,'DEURNE (BT.):::DIEST:::SCHAFFEN:::WEBBEKOM',3077);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3082,'regio drugpunt',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3083,'ASTENE:::BACHTE-MARIA-LEERNE:::DEINZE:::GOTTEM:::GRAMMENE:::MEIGEM:::PETEGEM-AAN-DE-LEIE:::SINT-MARTENS-LEERNE:::VINKT:::WONTERGEM:::ZEVEREN',3082);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3084,'MACHELEN (O.-VL.):::OLSENE:::ZULTE',3082);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3085,'EKE:::NAZARETH',3082);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3086,'DE PINTE:::ZEVERGEM',3082);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3087,'SINT-MARTENS-LATEM',3082);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3089,'Regio Lokeren-Berlare-Zele',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3090,'BERLARE:::OVERMERE:::UITBERGEN',3089);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3091,'ZELE',3089);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3092,'DAKNAM:::EKSAARDE:::LOKEREN',3089);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3094,'Regio AKM',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3095,'AALTER:::LOTENHULLE:::POEKE',3094);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3096,'KNESSELARE:::URSEL',3094);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3097,'MALDEGEM',3094);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3099,'Regio Rhode&Schelde',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3100,'GONTRODE:::MELLE',3099);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3101,'BOTTELARE:::LEMBERGE:::MELSEN:::MERELBEKE:::MUNTE:::SCHELDERODE',3099);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3102,'DESTELBERGEN:::HEUSDEN (O.-VL.)',3099);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3104,'Regio Elza',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3105,'ERTVELDE:::EVERGEM:::KLUIZEN:::SLEIDINGE',3104);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3106,'ASSENEDE',3104);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3107,'ZELZATE',3104);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3108,'BEERVELDE:::LOCHRISTI:::ZAFFELARE:::ZEVENEKEN',3104);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3110,'regio EEKASI',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3111,'EEKLO',3110);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3112,'KAPRIJKE',3110);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3113,'SINT-LAUREINS',3110);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3115,'Regio Wetteren_Laarne_Wichelen',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3116,'MASSEMEN:::WESTREM:::WETTEREN',3115);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3117,'KALKEN:::LAARNE',3115);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3118,'SCHELLEBELLE:::SERSKAMP:::WICHELEN',3115);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3120,'Regio INDRA',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3121,'AALST',3120);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3122,'AAIGEM:::BAMBRUGGE:::BURST:::ERONDEGEM:::ERPE:::ERPE-MERE:::MERE:::OTTERGEM:::VLEKKEM',3120);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3123,'IMPE:::LEDE:::OORDEGEM:::SMETLEDE:::WANZELE',3120);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3124,'DENDERHOUTEM:::HAALTERT:::HELDERGEM',3120);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3125,'DENDERLEEUW',3120);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3127,'Aalter Knesselare',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3128,'AALTER:::LOTENHULLE:::POEKE',3127);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3129,'KNESSELARE:::URSEL',3127);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3131,'RWO regio Sint Niklaas',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3132,'NIEUWKERKEN-WAAS:::SINT-NIKLAAS',3131);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3133,'DAKNAM:::EKSAARDE:::LOKEREN',3131);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3134,'BEVEREN-WAAS:::HAASDONK:::KALLO (BEVEREN-WAAS):::MELSELE:::VRASENE',3131);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3135,'DE KLINGE:::MEERDONK:::SINT-GILLIS-WAAS:::SINT-PAUWELS',3131);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3136,'KEMZEKE:::STEKENE',3131);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3137,'BAZEL:::KRUIBEKE:::RUPELMONDE',3131);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3138,'ELVERSELE:::STEENDORP:::TEMSE:::TIELRODE',3131);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3139,'WAASMUNSTER',3131);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3141,'Halle-Vilvoorde',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3142,'HALLE',3141);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3143,'PEUTIE:::VILVOORDE',3141);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3144,'ASSE:::BEKKERZEEL:::KOBBEGEM:::MOLLEM',3141);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3146,'Brussel-Halle-Vilvoorde',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3147,'BRUSSEL 1:::BRUXELLES 1',3146);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3148,'HALLE',3146);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3149,'PEUTIE:::VILVOORDE',3146);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3150,'ASSE:::BEKKERZEEL:::KOBBEGEM:::MOLLEM',3146);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3152,'MIdden en Zuid- West-Vlaanderen',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3153,'KORTRIJK',3152);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3154,'BEVEREN (ROESELARE):::OEKENE:::ROESELARE:::RUMBEKE',3152);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3156,'Ternat-Roosdaal-Asse-Affligem',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3157,'TERNAT',3156);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3158,'ONZE-LIEVE-VROUW-LOMBEEK:::PAMEL:::ROOSDAAL:::STRIJTEM',3156);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3159,'ASSE:::BEKKERZEEL:::KOBBEGEM:::MOLLEM',3156);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3160,'AFFLIGEM:::ESSENE:::HEKELGEM:::TERALFENE',3156);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3162,'Brussels Gewest',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3163,'BRUSSEL 1:::BRUXELLES 1',3162);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3164,'ANDERLECHT:::BRUSSEL 7:::BRUXELLES 7',3162);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3165,'BRUSSEL 4:::BRUXELLES 4:::ETTERBEEK',3162);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3166,'BRUSSEL 14:::BRUXELLES 14:::EVERE',3162);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3167,'BRUSSEL 9:::BRUXELLES 9:::JETTE',3162);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3168,'AUDERGHEM:::BRUSSEL 16:::BRUXELLES 16:::OUDERGEM',3162);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3169,'BRUSSEL 3:::BRUXELLES 3:::SCHAARBEEK:::SCHAERBEEK',3162);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3170,'BRUSSEL 17:::BRUXELLES 17:::WATERMAAL-BOSVOORDE:::WATERMAEL-BOITSFORT',3162);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3171,'GANSHOREN',3162);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3172,'BRUSSEL 8:::BRUXELLES 8:::MOLENBEEK-SAINT-JEAN:::SINT-JANS-MOLENBEEK',3162);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3174,'Intergemeentelijke samenwerking Zele-Berlare',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3175,'BERLARE:::OVERMERE:::UITBERGEN',3174);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3176,'ZELE',3174);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3178,'Regio Waas en Dender',1);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3180,'Intergmeentelijk St-Niklaas - Beveren',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3181,'BEVEREN-WAAS:::HAASDONK:::KALLO (BEVEREN-WAAS):::MELSELE:::VRASENE',3180);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3182,'NIEUWKERKEN-WAAS:::SINT-NIKLAAS',3180);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3184,'zorgregio VAGGA Ketsstraat',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3185,'ANTWERPEN 1',3184);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3186,'BRASSCHAAT',3184);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3187,'''S GRAVENWEZEL:::SCHILDE',3184);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3188,'MALLE:::OOSTMALLE:::WESTMALLE',3184);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3189,'MORTSEL',3184);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3190,'WIJNEGEM',3184);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3191,'BURCHT:::ZWIJNDRECHT',3184);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3192,'BRECHT:::SINT-JOB-IN-''T-GOOR:::SINT-LENAARTS',3184);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3193,'KAPELLEN (ANTW.)',3184);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3194,'ESSEN',3184);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3196,'Regio Waasland',1);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3198,'Vilvoorde en rand',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3199,'PEUTIE:::VILVOORDE',3198);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3200,'EPPEGEM:::ZEMST',3198);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3201,'KAPELLE-OP-DEN-BOS:::NIEUWENRODE:::RAMSDONK',3198);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3202,'GRIMBERGEN',3198);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3203,'MACHELEN (BT)',3198);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3204,'MELSBROEK:::PERK:::STEENOKKERZEEL',3198);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3205,'BERG (BT.):::BUKEN:::KAMPENHOUT:::NEDEROKKERZEEL',3198);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3207,'Asse en rand',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3208,'ASSE:::BEKKERZEEL:::KOBBEGEM:::MOLLEM',3207);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3209,'WEMMEL',3207);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3210,'DROESHOUT (OPWIJK):::MAZENZELE:::OPWIJK',3207);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3211,'DILBEEK:::SINT-MARTENS-BODEGEM:::SINT-ULRIKS-KAPELLE',3207);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3212,'BRUSSEGEM:::HAMME (BT.):::MERCHTEM',3207);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3213,'AFFLIGEM:::ESSENE:::HEKELGEM:::TERALFENE',3207);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3214,'TERNAT',3207);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3216,'ECAT Sint-Niklaas & Dendermonde',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3217,'APPELS:::BAASRODE:::DENDERMONDE:::GREMBERGEN:::MESPELARE:::OUDEGEM:::SCHOONAARDE:::SINT-GILLIS-BIJ-DENDERMONDE',3216);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3218,'NIEUWKERKEN-WAAS:::SINT-NIKLAAS',3216);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3220,'RWR Ieper',1);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3222,'Rhode en Schelde',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3223,'GONTRODE:::MELLE',3222);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3224,'BOTTELARE:::LEMBERGE:::MELSEN:::MERELBEKE:::MUNTE:::SCHELDERODE',3222);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3225,'DESTELBERGEN:::HEUSDEN (O.-VL.)',3222);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3227,'Pajottenland',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3228,'GOOIK:::KESTER:::LEERBEEK:::OETINGEN',3227);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3229,'GALMAARDEN:::TOLLEMBEEK:::VOLLEZELE',3227);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3230,'BEVER:::BIEVENE',3227);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3231,'HERFELINGEN:::HERNE',3227);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3232,'BOGAARDEN:::HEIKRUIS:::PEPINGEN',3227);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3233,'GAASBEEK:::LENNIK:::SINT-KWINTENS-LENNIK:::SINT-MARTENS-LENNIK',3227);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3235,'Faciliteitengemeenten (PW Haviland)',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3236,'WEMMEL',3235);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3237,'KRAAINEM',3235);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3238,'WEZEMBEEK-OPPEM',3235);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3239,'DROGENBOS',3235);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3240,'LINKEBEEK',3235);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3242,'KASTZE',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3243,'EPPEGEM:::ZEMST',3242);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3244,'BERG (BT.):::BUKEN:::KAMPENHOUT:::NEDEROKKERZEEL',3242);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3245,'MELSBROEK:::PERK:::STEENOKKERZEEL',3242);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3247,'haviland',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3248,'DROGENBOS',3247);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3249,'LINKEBEEK',3247);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3250,'KRAAINEM',3247);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3251,'WEZEMBEEK-OPPEM',3247);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3252,'WEMMEL',3247);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3254,'intergemeentelijke drugpreventie Gooik',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3255,'GALMAARDEN:::TOLLEMBEEK:::VOLLEZELE',3254);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3256,'HERFELINGEN:::HERNE',3254);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3257,'GOOIK:::KESTER:::LEERBEEK:::OETINGEN',3254);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3258,'BEVER:::BIEVENE',3254);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3259,'BOGAARDEN:::HEIKRUIS:::PEPINGEN',3254);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3260,'GAASBEEK:::LENNIK:::SINT-KWINTENS-LENNIK:::SINT-MARTENS-LENNIK',3254);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3262,'groot leuven',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3263,'KEERBERGEN',3262);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3264,'ROTSELAAR',3262);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3265,'HAACHT:::TILDONK:::WESPELAAR',3262);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3266,'BOORTMEERBEEK',3262);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3267,'BEGIJNENDIJK:::BETEKOM',3262);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3268,'TREMELO',3262);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3269,'LEUVEN',3262);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3270,'BIERBEEK:::KORBEEK-LO:::LOVENJOEL:::OPVELP',3262);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3271,'KORTENBERG',3262);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3273,'hageland',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3274,'DEURNE (BT.):::DIEST:::SCHAFFEN:::WEBBEKOM',3273);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3275,'ASSENT:::BEKKEVOORT',3273);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3276,'HOUWAART:::SINT-JORIS-WINGE:::TIELT (BT.):::TIELT-WINGE',3273);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3277,'GEETBETS:::GRAZEN',3273);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3278,'SCHERPENHEUVEL:::SCHERPENHEUVEL-ZICHEM',3273);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3279,'KORTENAKEN:::RANSBERG:::SINT-MARGRIETE(KORTENAKEN)',3273);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3280,'AARSCHOT:::GELRODE',3273);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3281,'BOST:::GOETSENHOVEN:::HAKENDOVER:::KUMTICH:::OORBEEK:::OPLINTER:::SINT-MARGRIETE-HOUTEM (TIENEN):::TIENEN:::VISSENAKEN',3273);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3283,'Regio Mechelen',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3284,'MECHELEN:::WALEM',3283);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3286,'Regio Antwerpen/Mechelen',1);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3288,'Regio Mechelen/Turnhout',1);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3290,'BODUKAP',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3291,'BONHEIDEN:::RIJMENAM',3290);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3292,'DUFFEL',3290);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3293,'SINT-KATELIJNE-WAVER',3290);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3294,'BEERZEL:::PUTTE',3290);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3296,'Rupel',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3297,'BOOM',3296);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3298,'SCHELLE',3296);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3299,'NIEL',3296);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3300,'REET:::RUMST:::TERHAGEN',3296);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3301,'HEMIKSEM',3296);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3303,'Halle-Vilvoorde',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3304,'HALLE',3303);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3305,'BEERSEL',3303);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3306,'DILBEEK:::SINT-MARTENS-BODEGEM:::SINT-ULRIKS-KAPELLE',3303);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3307,'ASSE:::BEKKERZEEL:::KOBBEGEM:::MOLLEM',3303);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3308,'PEUTIE:::VILVOORDE',3303);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3309,'NOSSEGEM:::ZAVENTEM',3303);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3310,'OVERIJSE',3303);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3311,'RHODE-SAINT-GENESE:::SINT-GENESIUS-RODE',3303);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3312,'OUDENAKEN:::SINT-LAUREINS-BERCHEM:::SINT-PIETERS-LEEUW',3303);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3313,'BOGAARDEN:::HEIKRUIS:::PEPINGEN',3303);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3315,'Regio Oostende',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3316,'OOSTENDE:::STENE:::ZANDVOORDE (OOSTENDE)',3315);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3317,'GISTEL:::MOERE:::SNAASKERKE:::ZEVEKOTE',3315);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3318,'BREDENE',3315);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3319,'MIDDELKERKE',3315);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3321,'politiezone spoorkin',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3322,'AVEKAPELLE:::BEAUVOORDE:::BOOITSHOEKE:::BULSKAMP:::DE MOEREN:::EGGEWAARTSKAPELLE:::HOUTEM (W.-VL.):::STEENKERKE (W.-VL.):::VEURNE:::VINKEM:::WULVERINGEM:::ZOUTENAAIE',3321);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3323,'ALVERINGEM:::HOOGSTADE:::OEREN:::SINT-RIJKERS',3321);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3324,'LO:::LO-RENINGE:::NOORDSCHOTE:::POLLINKHOVE:::RENINGE',3321);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3326,'kust',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3327,'BREDENE',3326);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3328,'BRUGGE:::KOOLKERKE',3326);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3329,'OOSTENDE:::STENE:::ZANDVOORDE (OOSTENDE)',3326);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3330,'MIDDELKERKE',3326);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3331,'ADINKERKE:::DE PANNE',3326);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3332,'DE HAAN:::KLEMSKERKE:::WENDUINE',3326);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3333,'BLANKENBERGE:::UITKERKE',3326);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3334,'KOKSIJDE:::OOSTDUINKERKE:::WULPEN',3326);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3335,'NIEUWPOORT:::RAMSKAPELLE (NIEUWPOORT):::SINT-JORIS (NIEUWPOORT)',3326);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3337,'Interlokale vereniging drugpreventie Noord-Pajot',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3338,'ASSE:::BEKKERZEEL:::KOBBEGEM:::MOLLEM',3337);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3339,'AFFLIGEM:::ESSENE:::HEKELGEM:::TERALFENE',3337);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3340,'ONZE-LIEVE-VROUW-LOMBEEK:::PAMEL:::ROOSDAAL:::STRIJTEM',3337);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3341,'TERNAT',3337);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3343,'Interlokale vereniging drugpreventie Pajottenland',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3344,'GOOIK:::KESTER:::LEERBEEK:::OETINGEN',3343);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3345,'GALMAARDEN:::TOLLEMBEEK:::VOLLEZELE',3343);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3346,'BEVER:::BIEVENE',3343);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3347,'HERFELINGEN:::HERNE',3343);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3348,'GAASBEEK:::LENNIK:::SINT-KWINTENS-LENNIK:::SINT-MARTENS-LENNIK',3343);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3349,'BOGAARDEN:::HEIKRUIS:::PEPINGEN',3343);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3351,'Interlokale vereniging drugpreventie Haacht-Bo-Kee',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3352,'HAACHT:::TILDONK:::WESPELAAR',3351);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3353,'BOORTMEERBEEK',3351);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3354,'KEERBERGEN',3351);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3356,'Interlokale vereniging drugpreventie Haviland',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3357,'WEMMEL',3356);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3358,'KRAAINEM',3356);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3359,'WEZEMBEEK-OPPEM',3356);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3360,'DROGENBOS',3356);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3361,'LINKEBEEK',3356);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3363,'Interlokale vereniging drugpreventie KASTZE',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3364,'EPPEGEM:::ZEMST',3363);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3365,'BERG (BT.):::BUKEN:::KAMPENHOUT:::NEDEROKKERZEEL',3363);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3366,'MELSBROEK:::PERK:::STEENOKKERZEEL',3363);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3368,'Interlokale vereniging drugpreventie BRT',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3369,'BEGIJNENDIJK:::BETEKOM',3368);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3370,'ROTSELAAR',3368);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3371,'TREMELO',3368);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3373,'ACV Gent-Eeklo',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3374,'GENT',3373);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3375,'EEKLO',3373);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3376,'ASTENE:::BACHTE-MARIA-LEERNE:::DEINZE:::GOTTEM:::GRAMMENE:::MEIGEM:::PETEGEM-AAN-DE-LEIE:::SINT-MARTENS-LEERNE:::VINKT:::WONTERGEM:::ZEVEREN',3373);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3378,'Regionaal Overleg Drugs Mechelen',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3379,'MECHELEN:::WALEM',3378);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3380,'BOOM',3378);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3381,'KONINGSHOOIKT:::LIER',3378);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3382,'HALLAAR:::HEIST-OP-DEN-BERG',3378);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3384,'Aalter-Knesselare',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3385,'AALTER:::LOTENHULLE:::POEKE',3384);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3386,'KNESSELARE:::URSEL',3384);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3388,'Regionaal Overleg Mechelen 8/1/2009',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3389,'BOOM',3388);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3390,'KONINGSHOOIKT:::LIER',3388);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3391,'HALLAAR:::HEIST-OP-DEN-BERG',3388);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3392,'MECHELEN:::WALEM',3388);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3394,'CGG-regio Antwerpen - De Pont',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3395,'KONINGSHOOIKT:::LIER',3394);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3396,'MECHELEN:::WALEM',3394);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3397,'BOOM',3394);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3399,'Regionaal Overleg Drugpreventie 20/4/2009',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3400,'BOOM',3399);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3401,'KONINGSHOOIKT:::LIER',3399);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3402,'MECHELEN:::WALEM',3399);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3403,'HALLAAR:::HEIST-OP-DEN-BERG',3399);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3405,'Regionaal Overleg Drugpreventie 13/7/2009',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3406,'BOOM',3405);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3407,'KONINGSHOOIKT:::LIER',3405);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3408,'MECHELEN:::WALEM',3405);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3409,'HALLAAR:::HEIST-OP-DEN-BERG',3405);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3411,'Regionaal Overleg Drugpreventie 16/12/2009',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3412,'BOOM',3411);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3413,'MECHELEN:::WALEM',3411);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3414,'KONINGSHOOIKT:::LIER',3411);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3415,'HALLAAR:::HEIST-OP-DEN-BERG',3411);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3417,'Regio Brugge',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3418,'BRUGGE:::KOOLKERKE',3417);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3419,'LOPPEM:::VELDEGEM:::ZEDELGEM',3417);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3420,'HERTSBERGE:::OOSTKAMP:::RUDDERVOORDE:::WAARDAMME',3417);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3421,'BEERNEM:::OEDELEM:::SINT-JORIS (BEERNEM)',3417);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3422,'KNOKKE:::KNOKKE-HEIST:::WESTKAPELLE',3417);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3423,'KNOKKE:::KNOKKE-HEIST:::WESTKAPELLE',3417);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3425,'RWR Veurne-Diksmuide',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3426,'AVEKAPELLE:::BEAUVOORDE:::BOOITSHOEKE:::BULSKAMP:::DE MOEREN:::EGGEWAARTSKAPELLE:::HOUTEM (W.-VL.):::STEENKERKE (W.-VL.):::VEURNE:::VINKEM:::WULVERINGEM:::ZOUTENAAIE',3425);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3427,'BEERST:::DIKSMUIDE:::DRIEKAPELLEN:::ESEN:::KAASKERKE:::KEIEM:::LAMPERNISSE:::LEKE:::NIEUWKAPELLE:::OOSTKERKE (DIKSMUIDE):::OUDEKAPELLE:::PERVIJZE:::SINT-JACOBS-KAPELLE:::STUIVEKENSKERKE:::VLADSLO:::WOUMEN',3425);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3428,'HANDZAME:::KORTEMARK:::WERKEN:::ZARREN',3425);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3429,'BOVEKERKE:::KOEKELARE:::ZANDE',3425);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3430,'HOUTHULST:::KLERKEN:::MERKEM',3425);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3431,'ALVERINGEM:::HOOGSTADE:::OEREN:::SINT-RIJKERS',3425);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3432,'LO:::LO-RENINGE:::NOORDSCHOTE:::POLLINKHOVE:::RENINGE',3425);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3433,'NIEUWPOORT:::RAMSKAPELLE (NIEUWPOORT):::SINT-JORIS (NIEUWPOORT)',3425);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3434,'KOKSIJDE:::OOSTDUINKERKE:::WULPEN',3425);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3435,'ADINKERKE:::DE PANNE',3425);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3437,'zorgregio Roeselare',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3438,'EMELGEM:::IZEGEM:::KACHTEM',3437);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3439,'BEVEREN (ROESELARE):::OEKENE:::ROESELARE:::RUMBEKE',3437);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3440,'MEULEBEKE',3437);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3441,'ARDOOIE',3437);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3442,'EGEM:::PITTEM',3437);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3443,'RUISELEDE',3437);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3444,'WINGENE:::ZWEVEZELE',3437);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3445,'LICHTERVELDE',3437);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3446,'OOSTROZEBEKE',3437);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3447,'INGELMUNSTER',3437);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3449,'Halle-Vilvoorde',1);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3451,'Waasland',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3452,'NIEUWKERKEN-WAAS:::SINT-NIKLAAS',3451);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3454,'CGG-regio Middelpunt',1);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3456,'CGG-regio VAGGA-Altox',1);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3458,'CGG-regio Gent',1);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3460,'CGG-regio Limburg',1);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3462,'CGG-regio Asse-Vilvoorde',1);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3464,'CGG-regio Leuven',1);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3466,'CGG-regio Sint-Niklaas',1);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3468,'CGG-regio Brussel',1);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3470,'CGG-regio Turnhout',1);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3472,'haacht',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3473,'KEERBERGEN',3472);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3474,'HAACHT:::TILDONK:::WESPELAAR',3472);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3475,'BOORTMEERBEEK',3472);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3477,'brt',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3478,'BEGIJNENDIJK:::BETEKOM',3477);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3479,'ROTSELAAR',3477);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3480,'TREMELO',3477);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3482,'haviland',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3483,'KRAAINEM',3482);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3484,'WEZEMBEEK-OPPEM',3482);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3485,'LINKEBEEK',3482);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3486,'DROGENBOS',3482);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3487,'WEMMEL',3482);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3489,'kastze',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3490,'BERG (BT.):::BUKEN:::KAMPENHOUT:::NEDEROKKERZEEL',3489);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3491,'MELSBROEK:::PERK:::STEENOKKERZEEL',3489);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3492,'EPPEGEM:::ZEMST',3489);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3494,'pajottenland',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3495,'BEVER:::BIEVENE',3494);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3496,'GALMAARDEN:::TOLLEMBEEK:::VOLLEZELE',3494);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3497,'HERFELINGEN:::HERNE',3494);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3498,'GOOIK:::KESTER:::LEERBEEK:::OETINGEN',3494);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3499,'GAASBEEK:::LENNIK:::SINT-KWINTENS-LENNIK:::SINT-MARTENS-LENNIK',3494);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3500,'BOGAARDEN:::HEIKRUIS:::PEPINGEN',3494);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3502,'tarl',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3503,'ONZE-LIEVE-VROUW-LOMBEEK:::PAMEL:::ROOSDAAL:::STRIJTEM',3502);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3504,'TERNAT',3502);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3505,'AFFLIGEM:::ESSENE:::HEKELGEM:::TERALFENE',3502);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3506,'ASSE:::BEKKERZEEL:::KOBBEGEM:::MOLLEM',3502);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3508,'Drugpunt-regio',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3509,'ASTENE:::BACHTE-MARIA-LEERNE:::DEINZE:::GOTTEM:::GRAMMENE:::MEIGEM:::PETEGEM-AAN-DE-LEIE:::SINT-MARTENS-LEERNE:::VINKT:::WONTERGEM:::ZEVEREN',3508);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3510,'MACHELEN (O.-VL.):::OLSENE:::ZULTE',3508);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3511,'DE PINTE:::ZEVERGEM',3508);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3512,'SINT-MARTENS-LATEM',3508);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3513,'EKE:::NAZARETH',3508);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3515,'Regio Turnhout',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3516,'OUD-TURNHOUT',3515);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3517,'TURNHOUT',3515);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3518,'KASTERLEE:::LICHTAART:::TIELEN',3515);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3519,'RAVELS',3515);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3521,'Regio Geel',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3522,'GEEL',3521);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3523,'OEVEL:::TONGERLO (ANTW.):::WESTERLO:::ZOERLE-PARWIJS',3521);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3524,'OLEN',3521);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3525,'EINDHOUT:::LAAKDAL:::VORST (KEMPEN)',3521);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3526,'MEERHOUT',3521);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3528,'Regio Mol',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3529,'BALEN',3528);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3530,'MOL',3528);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3531,'RETIE',3528);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3532,'DESSEL',3528);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3534,'Regio Herentals',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3535,'HERENTALS:::MORKHOVEN:::NOORDERWIJK',3534);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3536,'HERENTHOUT',3534);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3537,'GROBBENDONK',3534);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3539,'Regio Beerse',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3540,'BEERSE:::VLIMMEREN',3539);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3541,'GIERLE:::LILLE:::POEDERLEE:::WECHELDERZANDE',3539);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3542,'VORSELAAR',3539);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3544,'Regio Hoogstraten',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3545,'HOOGSTRATEN',3544);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3546,'MERKSPLAS',3544);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3547,'BAARLE-HERTOG',3544);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3548,'RIJKEVORSEL',3544);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3550,'Regio Herselt',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3551,'HERSELT:::RAMSEL',3550);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3552,'HOUTVENNE:::HULSHOUT:::WESTMEERBEEK',3550);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3554,'Kempen',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3555,'TURNHOUT',3554);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3556,'GEEL',3554);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3557,'MOL',3554);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3558,'HERENTALS:::MORKHOVEN:::NOORDERWIJK',3554);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3559,'HERSELT:::RAMSEL',3554);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3560,'HOOGSTRATEN',3554);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3561,'ARENDONK',3554);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3562,'BEERSE:::VLIMMEREN',3554);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3564,'Regio Dendermonde',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3565,'APPELS:::BAASRODE:::DENDERMONDE:::GREMBERGEN:::MESPELARE:::OUDEGEM:::SCHOONAARDE:::SINT-GILLIS-BIJ-DENDERMONDE',3564);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3566,'DENDERBELLE:::LEBBEKE:::WIEZE',3564);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3567,'BUGGENHOUT:::OPDORP',3564);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3568,'HAMME (O.-VL.):::MOERZEKE',3564);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3569,'WAASMUNSTER',3564);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3571,'JES',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3572,'BRUSSEL 1:::BRUXELLES 1',3571);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3573,'GENT',3571);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3574,'ANTWERPEN 1',3571);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3576,'Halle en rand',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3577,'HALLE',3576);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3578,'BEERSEL',3576);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3579,'RHODE-SAINT-GENESE:::SINT-GENESIUS-RODE',3576);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3581,'Brussel-Halle',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3582,'HALLE',3581);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3583,'PEUTIE:::VILVOORDE',3581);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3584,'GRIMBERGEN',3581);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3585,'BRUSSEL 1:::BRUXELLES 1',3581);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3587,'Pajottenland',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3588,'HALLE',3587);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3589,'BEERSEL',3587);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3591,'Zorgregio Kortrijk',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3592,'KORTRIJK',3591);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3593,'KUURNE',3591);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3594,'WAREGEM',3591);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3595,'HARELBEKE',3591);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3596,'LENDELEDE',3591);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3597,'DEERLIJK',3591);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3599,'Politiezone WOKRA',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3600,'KRAAINEM',3599);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3601,'WEZEMBEEK-OPPEM',3599);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3603,'Regio Aalst',1);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3605,'Regio Dendermonde',1);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3607,'Kempen',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3608,'GEEL',3607);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3609,'MOL',3607);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3610,'HERENTALS:::MORKHOVEN:::NOORDERWIJK',3607);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3611,'TURNHOUT',3607);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3613,'Regio LOGO Waasland',1);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3615,'ALLeRT',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3616,'AFFLIGEM:::ESSENE:::HEKELGEM:::TERALFENE',3615);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3617,'LIEDEKERKE',3615);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3618,'GAASBEEK:::LENNIK:::SINT-KWINTENS-LENNIK:::SINT-MARTENS-LENNIK',3615);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3619,'ONZE-LIEVE-VROUW-LOMBEEK:::PAMEL:::ROOSDAAL:::STRIJTEM',3615);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3620,'TERNAT',3615);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3622,'Faciliteitengemeenten',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3623,'DROGENBOS',3622);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3624,'LINKEBEEK',3622);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3625,'KRAAINEM',3622);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3626,'WEMMEL',3622);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3627,'WEZEMBEEK-OPPEM',3622);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3629,'Politiezone Rode',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3630,'RHODE-SAINT-GENESE:::SINT-GENESIUS-RODE',3629);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3631,'LINKEBEEK',3629);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3632,'DROGENBOS',3629);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3634,'TARL',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3635,'TERNAT',3634);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3636,'AFFLIGEM:::ESSENE:::HEKELGEM:::TERALFENE',3634);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3637,'ONZE-LIEVE-VROUW-LOMBEEK:::PAMEL:::ROOSDAAL:::STRIJTEM',3634);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3638,'LIEDEKERKE',3634);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3640,'Voorkempen',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3641,'BRECHT:::SINT-JOB-IN-''T-GOOR:::SINT-LENAARTS',3640);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3642,'LOENHOUT:::WUUSTWEZEL',3640);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3644,'Logo regio dender',1);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3646,'logo regio gezond plus',1);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3648,'Politiezone ARRO Ieper',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3649,'BRIELEN:::DIKKEBUS:::IEPER:::SINT-JAN',3648);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3650,'HEUVELLAND:::NIEUWKERKE',3648);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3651,'BIKSCHOTE:::LANGEMARK:::LANGEMARK-POELKAPELLE:::POELKAPELLE',3648);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3652,'MESEN:::MESSINES',3648);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3653,'DADIZELE:::MOORSLEDE',3648);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3654,'HARINGE (POPERINGE):::POPERINGE:::RENINGELST',3648);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3655,'OOSTNIEUWKERKE:::STADEN:::WESTROZEBEKE',3648);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3656,'OOSTVLETEREN:::VLETEREN:::WESTVLETEREN:::WOESTEN',3648);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3657,'GELUWE:::WERVIK',3648);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3658,'BESELARE:::GELUVELD:::PASSENDALE:::ZANDVOORDE (ZONNEBEKE):::ZONNEBEKE',3648);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3660,'regio leieland',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3661,'ANZEGEM:::GIJZELBRECHTEGEM:::INGOOIGEM:::VICHTE',3660);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3662,'DENTERGEM:::MARKEGEM:::OESELGEM:::WAKKEN',3660);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3663,'DEERLIJK',3660);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3664,'HARELBEKE',3660);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3665,'KORTRIJK',3660);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3666,'KUURNE',3660);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3667,'LAUWE:::MENEN:::REKKEM',3660);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3668,'ESPIERRES:::ESPIERRES-HELCHIN:::HELCHIN:::HELKIJN:::SPIERE:::SPIERE-HELKIJN',3660);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3669,'WAREGEM',3660);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3670,'GELUWE:::WERVIK',3660);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3672,'gerechtelijk arrondisement Ieper',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3673,'BRIELEN:::DIKKEBUS:::IEPER:::SINT-JAN',3672);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3674,'GELUWE:::WERVIK',3672);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3675,'HEUVELLAND:::NIEUWKERKE',3672);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3676,'MESEN:::MESSINES',3672);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3677,'HARINGE (POPERINGE):::POPERINGE:::RENINGELST',3672);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3678,'AVEKAPELLE:::BEAUVOORDE:::BOOITSHOEKE:::BULSKAMP:::DE MOEREN:::EGGEWAARTSKAPELLE:::HOUTEM (W.-VL.):::STEENKERKE (W.-VL.):::VEURNE:::VINKEM:::WULVERINGEM:::ZOUTENAAIE',3672);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3679,'BEERST:::DIKSMUIDE:::DRIEKAPELLEN:::ESEN:::KAASKERKE:::KEIEM:::LAMPERNISSE:::LEKE:::NIEUWKAPELLE:::OOSTKERKE (DIKSMUIDE):::OUDEKAPELLE:::PERVIJZE:::SINT-JACOBS-KAPELLE:::STUIVEKENSKERKE:::VLADSLO:::WOUMEN',3672);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3680,'HOUTHULST:::KLERKEN:::MERKEM',3672);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3681,'KOKSIJDE:::OOSTDUINKERKE:::WULPEN',3672);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3682,'NIEUWPOORT:::RAMSKAPELLE (NIEUWPOORT):::SINT-JORIS (NIEUWPOORT)',3672);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3684,'regio welzijnsraad Ieper',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3685,'BRIELEN:::DIKKEBUS:::IEPER:::SINT-JAN',3684);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3686,'HEUVELLAND:::NIEUWKERKE',3684);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3687,'GELUWE:::WERVIK',3684);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3688,'HARINGE (POPERINGE):::POPERINGE:::RENINGELST',3684);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3689,'OOSTVLETEREN:::VLETEREN:::WESTVLETEREN:::WOESTEN',3684);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3690,'MESEN:::MESSINES',3684);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3691,'BIKSCHOTE:::LANGEMARK:::LANGEMARK-POELKAPELLE:::POELKAPELLE',3684);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3692,'BESELARE:::GELUVELD:::PASSENDALE:::ZANDVOORDE (ZONNEBEKE):::ZONNEBEKE',3684);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3694,'regio logo midden-west-vlaanderen',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3695,'ARDOOIE',3694);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3696,'BEERST:::DIKSMUIDE:::DRIEKAPELLEN:::ESEN:::KAASKERKE:::KEIEM:::LAMPERNISSE:::LEKE:::NIEUWKAPELLE:::OOSTKERKE (DIKSMUIDE):::OUDEKAPELLE:::PERVIJZE:::SINT-JACOBS-KAPELLE:::STUIVEKENSKERKE:::VLADSLO:::WOUMEN',3694);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3697,'HEUVELLAND:::NIEUWKERKE',3694);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3698,'HOUTHULST:::KLERKEN:::MERKEM',3694);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3699,'GITS:::HOOGLEDE',3694);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3700,'BRIELEN:::DIKKEBUS:::IEPER:::SINT-JAN',3694);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3701,'INGELMUNSTER',3694);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3702,'EMELGEM:::IZEGEM:::KACHTEM',3694);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3703,'HANDZAME:::KORTEMARK:::WERKEN:::ZARREN',3694);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3704,'LENDELEDE',3694);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3706,'Regio CLB GO Tielt',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3707,'AARSELE:::KANEGEM:::SCHUIFERSKAPELLE:::TIELT',3706);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3708,'WAREGEM',3706);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3709,'ASTENE:::BACHTE-MARIA-LEERNE:::DEINZE:::GOTTEM:::GRAMMENE:::MEIGEM:::PETEGEM-AAN-DE-LEIE:::SINT-MARTENS-LEERNE:::VINKT:::WONTERGEM:::ZEVEREN',3706);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3710,'EEKLO',3706);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3711,'DE PINTE:::ZEVERGEM',3706);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3713,'Regio LOP Hamme',1);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3715,'Centrumsteden',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3716,'BEVEREN (ROESELARE):::OEKENE:::ROESELARE:::RUMBEKE',3715);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3717,'BRUGGE:::KOOLKERKE',3715);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3718,'KORTRIJK',3715);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3719,'OOSTENDE:::STENE:::ZANDVOORDE (OOSTENDE)',3715);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3721,'MSOC',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3722,'BEVEREN (ROESELARE):::OEKENE:::ROESELARE:::RUMBEKE',3721);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3723,'OOSTENDE:::STENE:::ZANDVOORDE (OOSTENDE)',3721);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3724,'KORTRIJK',3721);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3726,'CLUSTER_ONE1',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3727,'AARTSELAAR',3726);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3728,'ALKEN',3726);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3729,'BRUGGE:::KOOLKERKE',3726);
INSERT INTO Locations (id,Naam,IsCluster) VALUES (3731,'Politiezone AMOW',1);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3732,'ASSE:::BEKKERZEEL:::KOBBEGEM:::MOLLEM',3731);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3733,'BRUSSEGEM:::HAMME (BT.):::MERCHTEM',3731);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3734,'DROESHOUT (OPWIJK):::MAZENZELE:::OPWIJK',3731);
INSERT INTO Locations (id,Naam,ouder_id) VALUES (3735,'WEMMEL',3731);



